### ISSUE TITLE
Incorrect description in the README.md

### ISSUE THREAD

**Issue by Dimdron** [fitpay/fitpay-android-sdk#169]
Pre-compiled SDK is published on `maven() { url "https://dl.bintray.com/ross-fitpay/maven" }` instead of `jcenter()`.
Please, correct [this description](https://github.com/fitpay/fitpay-android-sdk#using-a-pre-built-version-of-the-sdk-as-a-dependency-for-your-build).

**Comment by jeremiahthomasharris** [comment]
@Dimdron As of version 0.6.0 the package is available via `jcenter()`.
